---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:314146295673:task-definition/spring-task-def:1"
        LoadBalancerInfo:
          ContainerName: "spring-cont"
          ContainerPort: 8080
